export const linksList = [
  { text: 'Home', to: '/', requireLogin: false, showAuthorizedUsers: true, requireAdmin: false },
  {
    text: 'Nosotros',
    to: '/nosotros',
    requireLogin: false,
    showAuthorizedUsers: true,
    requireAdmin: false,
  },
  {
    text: 'Contacto',
    to: '/contacto',
    requireLogin: false,
    showAuthorizedUsers: true,
    requireAdmin: false,
  },
  {
    text: 'Admin',
    to: '/admin',
    requireLogin: true,
    showAuthorizedUsers: true,
    requireAdmin: true,
  },
  {
    text: 'Registrarme',
    to: '/register',
    requireLogin: false,
    showAuthorizedUsers: false,
    requireAdmin: false,
  },
  {
    text: 'Ingresar',
    to: '/login',
    requireLogin: false,
    showAuthorizedUsers: false,
    requireAdmin: false,
  },
  {
    text: 'Cerrar sesión',
    to: '/logout',
    requireLogin: true,
    showAuthorizedUsers: true,
    requireAdmin: false,
  },
];
